Hello to the NexGen Cloud team,

Throughout my design career I have worked across many fields and highly technical environments and products. The Product Designer role description you have listed describes many of the fields that I have successfully delivered for businesses big and small. I have launched onboarding & account creation flows at Amber Labs and Octopus Deploy.I have worked in payment and funding gateways at Amber Labs, Corelogic (now Cototality), Swyftx, and Octopus Deploy. I have also delivered for end-to-end selection for product & subscription customisation for all these products from mobile applications to enterprise SaaS products. 

All of these roles have required a need for translating technical details & requirements from product owners, managers, & leads. This has been broken down and transformed into user scenarios, journey maps flows, opportunities and assumptions for testing. At times, the requirements document has not been fully realised which has required me to cover work from continuing discovery, discuss & knowledge share from stakeholders & users, to establish timelines, what do we need to find out, and organise resources. This work regardless of the state it is handed over to me, I have been able to come back to leads with a clear plan and workflow moving forward. 

Working on highly technical products in a small team has required me to independently work on research & discovery to help shape early assumptions for testing. These early assumptions lead into the generation of user journey maps, personas and scenarios that can help teams navigate their way to success from an early stage. I have conducted research using methods and tools such as, Dovetail, Amplitude, heat tracking tools, feedback & reviews, interviews, and desk research. All these help paint a vivid picture of customer pain points, needs, desires, and where best we can make changes. Whether these changes are small fixes or or enterprise features, they all can help to deliver the best possible product for them to achieve their goals. 

When I have started at companies working on purchasing portals and payment gateways, there has always been a disconnect and gap between the main line product, and the portal. This has even been apparent in some products I have worked on. Whether this is aesthetical, workflows not aligning, or a combination of both I have closed the gap between the pieces of the product & customer experience giving customers a more consistent experience during their customer lifecycle. This work has been successful through managing the end-to-end process of discovery, analysis, design, and delivery, but also having the full picture of what a user is looking to achieve and their goals by establishing a thorough journey map for them that  matches their mental model of the experience.


I am always excited to have work that is new and green to work on. I have been able to work with stakeholders previously creating strategies for products, features and the future of companies during my time at SaaS companies, start-ups, and during consultancy work. I would work with teams to help guide and lead them towards the goal of having a strategic plan for an outcome they desire  that balances and trades off between desirability, feasibility, viability, and usability. The goal here is to give the leadership and stakeholders a clear path forward and start to ideate on opportunities to work towards the outcomes they are looking for from the product. While work progresses, I make sure to regularly update and bring stakeholders along the journey.

I have worked at Octopus Deploy, a highly technical DevOps product, in their enterprise features team developing outcome driven solutions & tools and workflows that can work across entire cloud instances, not just a single project. I have worked directly with Product Leads, Owners, Managers, and other senior stakeholders where work may not be fully fleshed out when early discussions have started, but have ended with work broken into phases, current and ideal user flows, full journeys and what opportunities we can take to reach the desired outcome. I am practiced and efficient with user flow and scenario generation that helps break down a customers or users job to be done simply and digestible to stakeholders and assumption testing. I have self-led and owned projects and pitches that have turned into direct work, development, and features that have been delivered at internal and product level.

I believe my experience in developing and delivering  customer & user experiences for 7+ years around la-a-carte subscription services and financial systems will be a great benefit for NexGen Cloud. I am excited to be able to apply for a role at NexGen Cloud, and look forward to discussing this role in the future with you.

Hopefully hear from you soon,
Craig Johnson
