Hello Assembly Four team, 

Let me introduce myself. I am a product and user experience designer named Craig from Brisbane. 

I have a passion for highly considered and compassionate design practices, helping users to achieve their goals through research, testing and outcome driven design. I am a strong, collaborative worker who builds relationships in cross-functional, multi-disciplinary teams to help make sure communication and decisions work towards a collective outcome and bettering the user experience. I am an advocate of user and human centered design in all forms to help design solutions that address key problems, opportunities, and accessibility. I love to work with and talk to users when in discovery to help understand their needs better and build with inclusion, dignity and safety in mind in following UX heuristic best practices. 

In previous roles, I have held a design lead position to research, design and deploy new features. To uphold the responsibilities of the leadership position, and to achieve positive project outcomes, I have prioritised clear organisation and communication at all stages, particularly going into a project, I have refined scope and feature pitches alongside product owners and lead engineers, generated timelines to help with milestone management, written and conducted research plans, sourced interview participants, created and run interview scripts, created surveys, brought insights forward into potential opportunities and actions, built testable artefacts to bring into testing scenarios and situations, and iterated on concepts using findings and feedback to work towards a final realised solution. I practice a "Continuous Discovery" method that helps bring assumptions forward for testing with users and stakeholders to make sure outcomes meet the right balance of feasibility, desirability, viability, usability, and importantly, making sure the user and stakeholder opportunities are ethical.

I believe that a product can not be successful if it is not intentional in how it is designed. Success will come from a number of things: compassion for what the user's goals are, making sure accessibility standards are met as described in WCAG documents, developing and implementing intuitive flows for completing goals, and producing a consistent product in experience and appearance. Not only do these things help lead to a successful product, but also build trust and confidence with its user base. Having a focus on outcome based objectives helps to reflect what are the users needs and product goals. Also,  considering the outcome helps with the management process of making sure a product and its features maintain a high level of accessibility and inclusion, and represent a thoughtful purpose to the community of users.

I have built prototypes ranging from low fidelity pen and paper, digital wireframes, to high concept interactive prototypes for many projects and features. These have been generated using both managed design systems and component libraries, and assets that have been needed to be created for a specific purpose of helping the user complete a task. In the latter case, communication with engineering has been very important to make sure concepts and designs are feasible for delivery. All concepts are driven by making sure the flow and user journey is clear. I will always work from documents that help lay out the scenarios and objectives of a user when looking at a new feature so that a north star is visible and the concepts remain focused on the needs.

I am a practitioner of "Continuous Discovery" design and product management which has allowed me to take insights from interviews and feedback and responsively turn them into opportunities for feature and product improvements. Once documented, I have been able to generate and rank assumptions based on evidence and need based on user and stakeholder inputs.

Continuous Discovery is a framework that helps a product trio (designer, product owner, engineer) understand the needs of their users and stakeholders to optimise and decide on the right opportunities at any time. This framework relies on testing and iteration cycles that allows for assumptions to be brought forward for testing in interviews, conversations, all the way up to delivery. I have previously been in positions where management and organisation of opportunities has been required. The opportunities would have simple descriptions and were brought to stakeholders to help give input into where to direct attention. In following the Continuous Discovery process, as interviews occurred during these previous work scenarios, I remained  on the look out for more insights that could be taken and explored for future opportunities and direction, whether they be gaps in understanding or market, blockers and pain points, or missed engagements and touchpoints.

Following a Continuous Discovery framework, I have championed building relationships in cross-functional, multi-disciplined teams. I have been design lead on projects where I have worked closely with engineers and product owners, as a product trio, to make sure the outcomes can be met with tight timelines. These practices have helped in returning feasible and viable outcomes at the end of projects multiple times. When starting new work, I prioritise conversations with stakeholders at all levels to make sure that opportunities, scope, priorities, and outcomes are communicated and documented, giving the work a solid foundation moving forward. I practice and find it important to the success of products and experiences to make sure people are brought along during the discovery and design work, whether it is interviewing users for context, adjacent teams for compliance, consistency & promotion, and  stakeholders for deeper product and future vision context. These types of engagement in and outside of the company all help to build a more trusted and reliable product that its community is confident in using.

I have 8+ years of experience across enterprise SaaS solutioning, mobile apps, service platforms, and digital products. I have worked on and created corporate design systems & component libraries, admin portals, pathology job tracking, large data lake & warehouse optimisation, application redevelopment, payment gateways, devops tools, and exchange platforms. I am highly experienced in Figma and Figjam, as well as other UI and testing tools and graphic design products. I have made interactive prototypes for large and small cycle flows, as well as redeveloped existing, and created new & novel flows. I am experienced in Notion and Linear, as well as other software like Whimsical, Miro, Canva, JIRA, Confluence and others. I communicate well within and outside my team to help make sure problems are defined clearly and thoroughly, scenarios are considered and stakeholders are brought along through discovery & development. I am an adaptable designer who can pivot and shift when required, but can also focus and get to the root of a problem.

And most importantly, I want to help in creating products and solutions that help people gain more agency, safety, and empowerment. This is a very clear objective on applying for this role. All of these resources and internally message solutions really help with communication and making sure work visibility and tracking are consistently and confidently available through the stages of design. Depending on the audience, I employ different language, tone and concepts to help make information digestible for others. Whether it is internal or technological terminology to metaphor and scenarios, I can make people more comfortable and help their understanding of briefs and problems.

I have design experience working in support of marginalised communities with health and well-being concerns, including and considering the challenges of sensitive medical information around pathology testing & results from referral to outcomes being received by patients and medical professionals. I have an understanding of sex work, and have people in my life who have been or are currently involved in sex work. I have 3+ years of remote and async working experience and have worked in companies from 8 people in  fund and non-funded start-ups to 300 people nationally, up to global scale companies. Personally, I am diagnosed with AudHD and understand the complexities and uncertainty of the diagnosis process and the changes it can make to everyday life.

I feel very fortunate to have the opportunity to apply for a role in a company like Assembly Four and to work on your mission of empowering sex workers through technology with dignity and respect.

I look forward to hearing back from you,
Craig Johnson
